### ISSUE TITLE
Control for `attributes` parameter

### ISSUE THREAD

**Issue by nilsnolde** [traffordDataLab/leaflet.reachability#1]
Might be of interest to include the `reachability` attribute to the isochrone output or alternatively add a control parameter for which [`attributes`](https://openrouteservice.org/dev/#/api-docs/isochrones/get) to get.

Also, we have a new `smoothing` parameter. It's not really documented yet, but it's working. [Here](https://github.com/GIScience/openrouteservice/pull/245/commits/95b8e371b77e0a78d48dad12b51b9210529e31bb#diff-47cdf1ab4d656d1eb14fd1ae9e62553dR185) you can see some documentation on it inline. Its range is [0.0, 1.0] and it's a float.

**Comment by itsozz** [comment]
Hi Nils, thanks very much for the suggestions. Regarding the first point, just checking I'm correct that this is the `reachfactor` attribute? If so, is there any further information available on this other than what is mentioned in the [API docs](https://openrouteservice.org/documentation/#/reference/isochrones/isochrones/isochrones-service) that it is a score between 0 and 1? e.g. What the score is based on etc.

I'll have a look at the `smoothing` parameter as well, thanks for letting me know.

**Comment by nilsnolde** [comment]
Oops, so sorry, didn't see this one. 

You're right, it's not documented.. It basically calculates the ratio of actual isochrone area over the theoretically possible area one could reach if there were no roads (i.e. as the crow flies). That assumes a certain speed and is not actually modelled like the routing, just a plain circular "isochrone/equidistant" with constant mode speed. Hope you understood what I mean.

We're rebuilding a bit of that currently, since these constant speeds were waaay too high (50 km/h for bike haha), so reachibility was ALWAYS < 0.2 or so, even in super accessible areas like central squares in cities.

**Comment by itsozz** [comment]
No problem at all Nils, really appreciate your feedback and input.  Thanks very much for the clarification.  Please could you let us know when you've finished updating this aspect?

**Comment by itsozz** [comment]
Hi @nilsnolde, just picking up on this one again whilst preparing the new version of the plugin to use the V2 API.  I've implemented the `smoothing` parameter and am now looking at `reachfactor`.  Please can you confirm that `reachfactor` is only returned when `range_type` = "time" not "distance"?

**Comment by nilsnolde** [comment]
Hm, shouldn't be, but you're right! I'll look into it real quick and might open an issue on our side.

**Comment by itsozz** [comment]
Thanks as always Nils for your fast response. Hope it's not a pain to fix!

**Comment by nilsnolde** [comment]
No worries:)

I actually did fix that while fixing general issues with `reachfactor` [here](https://github.com/GIScience/openrouteservice/commit/37235c6b8aba823c4160f011ee7c76df08c95350). However, it's not in `master` yet, which confuses me a little. Let me talk to our git lord tmrw when he's back and get back to this.

**Comment by itsozz** [comment]
That's great, glad you've already fixed it! I'll handle it in the plugin so that if `reachfactor` is requested and it's not available it won't error, then when your change is present in `master` it will just work as expected.

Thanks again Nils!

**Comment by itsozz** [comment]
Release v2.0.0 implements everything discussed here so closing this now. Nils, please feel free to add further comments regarding `reachfactor` if neccessary.  Thanks very much.
