### ISSUE TITLE
Is the demo working?

### ISSUE THREAD

**Issue by tordans** [traffordDataLab/leaflet.reachability#2]
When I open https://rawgit.com/trafforddatalab/leaflet.reachability/master/leaflet.reachability_example.html I dont see any layer. I can open the menu on the left, but changing things there does not change anything on the map.

Am I doing it wrong?

**Comment by rcatlord** [comment]
Hi Tobias,

Thanks for your interest in the reachability plugin. I've checked the demo and it seems to be working fine.

![leaflet.reachability plugin demo](https://media.giphy.com/media/1O3lzAC2HlLsV6sQaV/200w_d.gif)

Have a look at our [video tutorials](https://vimeo.com/user71230875) for more info. 

Best wishes,

Henry
