### ISSUE TITLE
Angular project

### ISSUE THREAD

**Issue by rudyhadoux** [traffordDataLab/leaflet.reachability#7]
Hi,

Is there a way to insert this lib in an Angular project ?

**Comment by itsozz** [comment]
Hi. I'm afraid I don't use Angular so can't give you particular advice on how to do this, however I found the following which might be useful for you:

[https://codehandbook.org/use-leaflet-in-angular/](https://codehandbook.org/use-leaflet-in-angular/)

This library has been wrapped into an R package so I can't see why you wouldn't be able to use it in Angular or other frameworks.

Hope that helps.  Good luck with the project and thanks for your interest in the plugin.

**Comment by rudyhadoux** [comment]
1. Thanks for the useful link. With Angular there are @types and npm libs.
2. How does OpenRouteService collect road traffic records ?
3. Does your plugin take the time into account ? Because road traffic depends on the time.

**Comment by itsozz** [comment]
No worries. Regarding the questions concerning [OpenRouteService](https://openrouteservice.org/), I don't know I'm afraid, you would need to ask them as it's their API. However the plugin itself doesn't take the time of day into account. All it does is to provide a way to query the OpenRouteService Isochrones API and display the results all from within a Leaflet map.

**Comment by rudyhadoux** [comment]
I will ask them indeed. Thanks.
